# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_auto_20171112_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=20, verbose_name='Token')),
                ('description', models.TextField(max_length=200, verbose_name='Observacoes')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='address_city',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_state',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_street',
            field=models.CharField(max_length=100, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=4, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('new', 'Novo'), ('used', 'Usado')], max_length=5, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payment',
            field=models.CharField(max_length=20, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='token',
            field=models.CharField(max_length=20, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='validade',
            field=models.CharField(max_length=2, verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis',
            field=models.CharField(max_length=50, verbose_name='Chassi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometer',
            field=models.CharField(max_length=6, verbose_name='Kilometragem'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=8, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.Client'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.Client'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.Product'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.Service'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.Vehicle'),
        ),
    ]
