# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_auto_20171115_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.Client'),
        ),
    ]
