# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_auto_20171115_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='services',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='vehicle',
        ),
    ]
