# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0005_auto_20171115_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='state',
            field=models.CharField(choices=[('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('WAITING', 'Aguardando')], default='WAITING', max_length=11, verbose_name='Situacao'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='state',
            field=models.CharField(choices=[('PAYED', 'pago'), ('UNPAYED', 'nao pago')], default='UNPAYED', max_length=10, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('NEW', 'Novo'), ('USED', 'Usado')], max_length=5, verbose_name='Estado'),
        ),
    ]
