# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0006_auto_20171115_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('NEW', 'Novo'), ('USED', 'Usado')], max_length=5),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='items',
        ),
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.ManyToManyField(to='oficina.Product'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payment',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='services',
        ),
        migrations.AddField(
            model_name='quotation',
            name='services',
            field=models.ManyToManyField(to='oficina.Service'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='state',
            field=models.CharField(choices=[('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('WAITING', 'Aguardando')], default='WAITING', max_length=11),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='token',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='validade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='state',
            field=models.CharField(choices=[('PAYED', 'pago'), ('UNPAYED', 'nao pago')], default='UNPAYED', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometer',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
