# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0007_auto_20171115_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
