# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 00:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0008_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='validade',
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity',
            field=models.PositiveIntegerField(default='2', validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='payment',
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment',
            field=models.ManyToManyField(to='oficina.PaymentMethod'),
        ),
    ]
